name: Javascript app
on:
  push:
    branches: [ "main" ]
jobs:
  backend-check-code:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        version: '24'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    - run: npm install
    - run: npm run build --if-present
  backend-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Build x
        uses: docker/setup-buildx-action@v3
      - name: Build and push app
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: doc12mp/mysql_app:security_back
          context: "{{defaultContext}}:backend"
          build-args: |
            PORT=${{ secrets.PORT }}
            DB_KEY=${{ secrets.DB_KEY }}
            RANDOM_KEY=${{ secrets.RANDOM_KEY }}
  frontend-check-code:
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash
          working-directory: ./frontend
      steps:
        - name: Check out repository code
          uses: actions/checkout@v5
        - name: Set up Node
          uses: actions/setup-node@v4
          with:
            version: '24'
            cache: 'npm'
            cache-dependency-path: frontend/package-lock.json
        - run: npm install
        - run: npm run build --if-present
  frontend-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Build x
        uses: docker/setup-buildx-action@v3
      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: doc12mp/mysql_app:security_front
          context: "{{defaultContext}}:frontend"
      - name: Build and push nginx
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: doc12mp/mysql_app:security_nginx
          context: "{{defaultContext}}:frontend/nginx"
